source 'https://rubygems.org'
ruby '2.2.2'

gem 'sinatra', '>= 2.0.0'
gem 'sinatra-flash', '>= 0.3.0'
gem 'sinatra-contrib', '>= 2.0.0'
gem 'shotgun', '>= 0.9.1'
gem 'zurb-foundation'
gem 'compass'
gem 'rake'
gem 'pony'
gem 'faker'
gem 'uuid'
